### ISSUE TITLE
Define a mechanism to get message box offset used to generate storage proof in confirm stake intent service

### ISSUE THREAD

**Issue by sarvesh-ost** [mosaicdao/facilitator#141]
Facilitator currently uses fix value for message bus offset which is 7, but EIP20Gateway gateway with release 0.11.0 has different message bus offset. 

This ticket is about implementing a strategy to handle both kinds of gateways.

**Comment by deepesh-kn** [comment]
Suggestion: This can be done on the basis of the code hash. The implementer can come up with a better strategy.
