### ISSUE TITLE
Add model validations in repository.

### ISSUE THREAD

**Issue by deepesh-kn** [mosaicdao/facilitator#157]
Add a validate function that validates the model data before saving in the database.

- AuxiliaryChainRepository
- ContractEntityRepository
- GatewayRepository
- MessageRepository
- StakeRequestRepository

Check for the mandatory params are not null.

**Comment by pgev** [comment]
Please, make the function private and use it in save function itself as a precondition.

**Comment by abhayks1** [comment]
This ticket can be done after updating sequelize upsert to create/update/save.
Create/Update/Save sequelize methods does validation. 
Revisit this ticket after completion of ticket #158

**Comment by abhayks1** [comment]
The ticket can be closed since valdiations are taken care in #158

**Comment by deepesh-kn** [comment]
Validations related to values are already available in repositories files. Closing this issue
