### ISSUE TITLE
Add log level in facilitator start command.

### ISSUE THREAD

**Issue by deepesh-kn** [mosaicdao/facilitator#159]
- Accept the log level while starting the facilitator. Default logs will be off
- Accept the log path so that facilitator can write the logs in that file. Default logs will be on console.

**Comment by abhayks1** [comment]
This ticket is already implemented. This ticket can be closed.

**Comment by deepesh-kn** [comment]
Closing as its already implemented in https://github.com/mosaicdao/facilitator/pull/136
