### ISSUE TITLE
Facilitator start uts observer error

### ISSUE THREAD

**Issue by gulshanvasnani** [mosaicdao/facilitator#194]
Below error is encountered when facilitator starts :
error: Observer error: Error: GraphQL error: Invalid value provided for argument `orderBy`: Enum("uts")

**Comment by puneet-khushwani-eth** [comment]
This was because we had not added `uts` column to schema.

**Comment by puneet-khushwani-eth** [comment]
Closed via https://github.com/mosaicdao/mosaic-chains/pull/148. Fix would be available in 0.1.0-alpha.3 of mosaic-chains
