### ISSUE TITLE
Create systemctl commands for running  fault-tolerant instance(s) for facilitator

### ISSUE THREAD

**Issue by puneet-khushwani-eth** [mosaicdao/facilitator#202]
1. Determine machine(s) on which we would need to host these instances
2. commands could be like `systemctl start facilitator_{token_identifier}_{instance_identifier}`
ex.  `systemctl start facilitator_ost_1`

**Comment by abhayks1** [comment]
Closing the ticket in favour of: https://github.com/mosaicdao/facilitator/pull/228#pullrequestreview-303242712
