### ISSUE TITLE
Setup schema.graphql, mapping(handler), schema, subgraph.yml file for ERC20Gateway contract

### ISSUE THREAD

**Issue by deepesh-kn** [mosaicdao/facilitator#275]
- Define the entities in schema.graphq
```
DeclaredDepositIntent
      - id
      - token address
      - amount
      - nonce
      - beneficiary
      - fee gas price
      - fee gas limit
      - depositor
      - block number
      - block hash
      - contract address
      - updated time stamp (uts)

ConfirmedWithdrawIntent
      - id
      - message hash
      - block number
      - block hash
      - contract address
      - updated time stamp (uts)

ProvenGateway
      - id
      - proven block number
      - storage root
      - gateway address 
      - block number
      - block hash
      - contract address
      - updated time stamp (uts)
```
- Define handlers 
  - DeclaredDepositIntent, 
  - ConfirmedWithdrawIntent
  - ProvenGateway
- Add ABIs of
  - ERC20Gateway contract
- Events in subgraph.yaml
  - DepositIntentDeclared event
  - WithdrawIntentConfirmed event
  - GatewayProven event

**Comment by Vindeep07** [comment]
In entity ProvenGateway, storage root field is not emitted from event GatewayProven. Do we need `storageRoot` field in ProvenGateway entity ?

**Comment by Vindeep07** [comment]
In PR #330  ,  `address` for ERC20Gateway contract in subgraph.yaml is set to dummy address, and should be changed after contract deployment.
cc: @deepesh-kn
