### ISSUE TITLE
Implement Anchor model and Anchor repository.

### ISSUE THREAD

**Issue by deepesh-kn** [mosaicdao/facilitator#281]
- Anchor Model
  - Extends Comparable
```
Anchor
        - anchorGA
        - lastAnchoredBlockNumber
```
- AnchorRepository
  - Extends Subject
  - Functions
    - AnchorRepository::init
    - AnchorRepository::save
    - AnchorRepository::get

**Comment by pgev** [comment]
Draft PR: https://github.com/mosaicdao/facilitator/pull/310
