### ISSUE TITLE
Implement ContractEntity model and ContractEntity repository. 

### ISSUE THREAD

**Issue by deepesh-kn** [mosaicdao/facilitator#284]
1. Move `ContractEntity.ts` in the common/models directory, rename to ContractEntityBase.
2. Update the `ContractEntityBase.ts` as follows:
  - remove `enum EntityType` form the class.
  - remove `public entityType` variable.
  - remove `entityType` from constructor param.
  - In compareTo function use `this.getEntityType() as string` instead of `this.entityType`.

3. Implement ContractEntity.ts in M0 and M1 models that extends `ContractEntityBase`.
4. In M0 ContractEntity add `enum EntityType` related to M0 facilitator.
5. In M1 ContractEntity add `enum EntityType` related to M1 facilitator.
6. M0 and M1 will implement `getEntityType(): string` function that returns the enity as string.

-~~ContractEntity Model~~
  - ~~Extends Comparable~~
```
~~ContractEntity~~
  - ~~contract address~~
  - ~~entity~~
  - ~~timestamp~~
```
- ~~ContractEntityRepository~~
  - ~~Extends Subject~~
  - ~~Functions~~
    - ~~ContractEntityRepository.init~~
    - ~~ContractEntityRepository::save~~
    - ~~ContractEntityRepository::get~~

**Comment by pgev** [comment]
Moving to parking lot after discussion with @deepesh-kn as ticket needs to be enhanced and specd out.

**Comment by gulshanvasnani** [comment]
As discussed with @deepesh-kn , @sarvesh-ost , @abhayks1 , 
1. Make ContractEntity model's, `entityType` fields generic.
2. Change `EntityType` enum to `M0EntityType`.
3. Introduce new `M1EntityType` enum for all the subgraph entities required for M1 subgraph.
4. Move ContractEntity and ContractEntityRepository to `common` folder.

**Comment by abhayks1** [comment]
I have created proposal in below branch using arrays. Idea is whenever ContractEntity Model object is created, entity types should be validated. In respective Constant.ts of M0 and M1 facilitator, entity types are defined. 
https://github.com/abhayks1/facilitator/commit/874d52bb01da0d964a3093a9655fa80f966af7fe

cc: @deepesh-kn
