### ISSUE TITLE
Implement facilitator start

### ISSUE THREAD

**Issue by deepesh-kn** [mosaicdao/facilitator#290]
Implement facilitator start
  - Validates the provided `manifest.yaml` file.
  - Check if the seed data is populated as per the provided manifest file.
  - Subscribes to the origin graph node for the entities
  - Subscribes to the auxiliary graph node for the entities
  - Resubscribes to the graph nodes after a fixed interval.
  - [Move the common code]

**Comment by pgev** [comment]
Implementation is ready. Moving back to backlog as I will be out 9, 10 and 11.
