### ISSUE TITLE
Implement ProveGateway service

### ISSUE THREAD

**Issue by deepesh-kn** [mosaicdao/facilitator#302]
Prove gateway
- Generate the account proof.
- Generate raw transaction for proof account
- Call transaction executor.

**Comment by kreloaded** [comment]
Completed tasks:
Implemented ProveGatewayService
Tests for GatewayRepository::getByAnchor

Remaining tasks:
Tests for ProveGatewayService

Branch Link: https://github.com/kreloaded/facilitator/tree/service_prove_gateway
