### ISSUE TITLE
Facilitator init should also support Anchor::getLatestStateRootBlockHeight method to fetch latest block number

### ISSUE THREAD

**Issue by abhayks1** [mosaicdao/facilitator#357]
M1 anchor contract method name is getLatestStateRootBlockNumber to fetch latest state root block number.
M0 anchor method name is getLatestStateRootBlockHeight.
Facilitator init should support both getLatestStateRootBlockNumber as well as getLatestStateRootBlockHeight.

**Comment by 0xsarvesh** [comment]
I don't think we should update the implementation and only call`getLatestStateRootBlockHeight`. Alternatively, we could accept flag in init command based on that anchorInteract can be invoked.

**Comment by abhayks1** [comment]
You mean support both M0 and M1 anchor contracts?

**Comment by 0xsarvesh** [comment]
Yea, Or make M1 anchor backward compatible
